title: Madhur Anand
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://shutdownkiya.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: really
   url: /index.html
 - title: whoami
   url: /about
 - title: lala
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: madhur.rover
   email: madhuranand@live.in

google_analytics: ""
